# Generated by Django 5.0.2 on 2024-03-24 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderquantity', models.PositiveIntegerField(null=True)),
                ('dates', models.DateTimeField(auto_now_add=True)),
                ('productmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HamroDokan.productmodel')),
                ('staffmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
