# Generated by Django 5.0.2 on 2024-03-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0002_ordermodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'Shop List'},
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='nameofquantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
