# Generated by Django 5.0.2 on 2024-03-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0005_userprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='address',
            field=models.CharField(default='Your Default Value', max_length=100),
        ),
    ]
