# Generated by Django 5.0.2 on 2024-03-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0006_userprofilemodel_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='address',
        ),
    ]
