# Generated by Django 5.0.2 on 2024-03-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0008_remove_userprofilemodel_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
