# Generated by Django 5.0.2 on 2024-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0009_userprofilemodel_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='', upload_to='vendor_images'),
        ),
    ]
