# Generated by Django 5.0.2 on 2024-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0010_productmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
