# Generated by Django 5.0.2 on 2024-04-01 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0011_productmodel_whatsapp_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image',
            new_name='imageshop',
        ),
    ]
