# Generated by Django 5.0.2 on 2024-04-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0012_rename_image_productmodel_imageshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='vendor_unique_identifier',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
