# Generated by Django 5.0.2 on 2024-04-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HamroDokan', '0013_userprofilemodel_vendor_unique_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='vendor_unique_identifier',
        ),
    ]
